global:
  scrape_interval: 5s

rule_files:
  - alert.rules.yml
  
scrape_configs:
  - job_name: "student-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["student-backend:3000"]
