name: Node.js CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🟦 Checkout Code
        uses: actions/checkout@v3

      - name: 🟩 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 🟧 Install Dependencies
        run: npm install

      - name: 🟪 Set up MongoDB Atlas URL
        env:
          MONGO_URL: "mongodb+srv://vrehemanth4_db_user:cgbNqmtB0Vt7wi2P@cluster0.uiivf00.mongodb.net/?appName=Cluster0"
        run: echo "MONGO_URL Loaded"

      - name: 🟥 Run Unit Tests
        env:
          MONGO_URL: "mongodb+srv://vrehemanth4_db_user:cgbNqmtB0Vt7wi2P@cluster0.uiivf00.mongodb.net/?appName=Cluster0"
        run: npm test
